-- 1. テーブルの作成
create table coffee_pairings (
  id bigint generated by default as identity primary key,
  roast_level text not null,   -- 焙煎度 (例: 浅煎り)
  food_category text not null, -- カテゴリ (例: スイーツ)
  menu_name text not null,     -- メニュー名 (例: レモンタルト)
  reason text not null         -- 理由
);

-- 2. セキュリティ設定（テスト用：誰でも読み取れるように設定）
alter table coffee_pairings disable row level security;

-- 3. データの投入（サンプルデータ）
insert into coffee_pairings (roast_level, food_category, menu_name, reason) values
('浅煎り', '食事', '冷製パスタ・サラダボウル', 'コーヒーの酸味がドレッシング代わりになり、野菜の味を引き立てます。'),
('浅煎り', 'スイーツ', 'レモンタルト・アップルパイ', 'フルーツの酸味とコーヒーの酸味が同調し、爽やかな余韻を楽しめます。'),
('中煎り', '食事', 'オムライス・たまごサンド', '卵の甘みやケチャップの酸味を、バランスの良いコーヒーが包み込みます。'),
('中煎り', 'スイーツ', 'ドーナツ・フィナンシェ', '小麦やアーモンドの香ばしさと、コーヒーのナッツ感がマッチします。'),
('深煎り', '食事', 'カレーライス・ピザ', 'スパイスやチーズの濃厚な味に、深煎りの強いボディ感は負けません。'),
('深煎り', 'スイーツ', 'チョコレートケーキ・チーズケーキ', '濃厚でクリーミーな甘さを、強い苦味がすっきりと流してくれます。');
